coffe_shop/coffe_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include("products.urls")),
    path('users/', include("user.urls")),
    path('orders/', include("orders.urls"))
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

coffe_shop/orders/urls.py
from django.urls import path
from .views import MyOrderView

urlpatterns = [
    path('mi-orden/', MyOrderView.as_view(), name = "my_order" )

]

coffe_shop/products/urls.py
from django.urls import path

from.views import ProductFormView, ProductLisView

urlpatterns = [
    path('agregar', ProductFormView.as_view(), name= "add_product"),
    path('listado', ProductLisView.as_view(), name ="listado")
]   

coffe_shop/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView
from django.urls import path


urlpatterns = [
    path('login/',
          LoginView.as_view(template_name = "users/login.html"),
          name = "login"),
    path('logout/',LogoutView.as_view(), name= "logout"),
    path('create/', RegisterView.as_view(), name = 'create')
    ]

coffe_shop/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Products
# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"orders {self.id} by {self.user}"
    

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.order} - {self.product}"

coffe_shop/products/models.py
from django.db import models

# Create your models here.


class Products(models.Model):
    name = models.TextField(max_length=200, verbose_name="nombre")
    description = models.TextField(max_length=300, verbose_name="descripción")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="precio")
    available = models.BooleanField(default=True, verbose_name="disponible")
    photo = models.ImageField(upload_to="./logos",null = True, blank=True, verbose_name="foto")
    #time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

coffe_shop/user/models.py
from django.db import models

# Create your models here.

coffe_shop/products/forms.py
from django import forms
from .models import Products

class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label= "Descripción")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    available = forms.BooleanField(initial=True, label="Disponible", required=True)
    photo = forms.ImageField(label = "Foto", required= False)

    def save(self):
        Products.objects.create(
            name = self.cleaned_data["name"],
            description = self.cleaned_data["description"],
            price = self.cleaned_data["price"],
            available = self.cleaned_data["available"],
            photo = self.cleaned_data["photo"],
        )

coffe_shop/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.views.generic import DetailView
from .models import Order

# Create your views here.

class MyOrderView(LoginRequiredMixin,DetailView):
    model = Order
    template_name = "orders/my-order.html"
    context_object_name = "order"

    def get_object(self, queryset = None):
        order =Order.objects.filter(is_active = True, user = self.request.user).first()
        print(order)
        return order

coffe_shop/products/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import FormView, ListView
from .forms import ProductForm
from .models import Products

# Create your views here.

class ProductFormView(FormView):
     template_name = "products/add_product.html"
     form_class = ProductForm
     success_url = reverse_lazy("listado")

     def form_valid(self, form):
          form.save()
          return super().form_valid(form)
     
class ProductLisView(ListView):
     model = Products
     template_name = "products/product_list.html" 
     context_object_name = "products"    

     # def get_context_data(self):
     #      list_products = Products.objects.all()
     #      return {"list_products": list_products}

coffe_shop/user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


# Create your views here.

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

coffe_shop/orders/templates/orders/my-order.html
{% extends "base.html" %}

{% block content %} 
Estamos dentro
{{order.user.username}}
{{order.order_date | date}}

{% for product_order in order.orderproduct_set.all%}
{{ product_order.product.name}}
<br>
{{ product_order.product.price}}
<br>
{{ product_order.quantity}}

{%empty%}
No hay items en tu orden
{% endfor%}



{% endblock content %}

coffe_shop/products/templates/products/add_product.html
Acá aparecerá el Form

<form action="{% url "add_product" %}" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit">Agregar</button>
</form>

coffe_shop/products/templates/products/product_list.html
{% extends "base.html" %}
{%block content%}
<h1 class="text-3xl font-bold underline">
    Lista de Productos
   </h1>
<div class="grid grid-cols-1 gap-4 md:grid-cols-4 md:gap-8 mt-8">
{% for product in products%}    
<div class="h-32 rounded-lg bg-gray-200">
<a href="#" class="group relative block overflow-hidden">
  <button
    class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
  >
    <span class="sr-only">Wishlist</span>

    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="size-4"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
      />
    </svg>
  </button>
  {% if product.photo %}
  <img
    src="{{product.photo.url}}"
    alt="{{product.name}}"
    class="h-full w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
  />
  {% endif%}
  <div class="relative border border-gray-100 bg-white p-6">
    <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"> New </span>

    <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.name}}</h3>

    <p class="mt-1.5 text-sm text-gray-700">{{product.price}}</p>
    <p class="mt-1.5 text-pretty text-xs text-gray-500">
      {{product.description}}
  </p>
    <p>{{product.available}}</p>
    {% comment "" %}
    <form class="mt-4">
      <button
        class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
      >
        Add to Cart
      </button>
    </form>
    {% endcomment %}
  </div>
</a>
</div>
<br>
{%endfor%}
</div>
{%endblock content%}

coffe_shop/templates/base.html
<html>
    <head>
        <title>Coffee shop</title>
        
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <header class="bg-white">
        <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
          <div class="flex flex-col items-start gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Blog Posts</h1>
      
              <p class="mt-1.5 text-sm text-gray-500">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure, recusandae.
              </p>
            </div>
      
            <div class="flex items-center gap-4">
              <button
                
                type="button"
              >                
                {%if user.is_authenticated%}               
               
                <form action = "{%url "logout"%}" method = "post" class="text-sm font-medium">
                    {%csrf_token%}            
                    <button 
                    class="inline-flex items-center justify-center gap-1.5 rounded border border-gray-200 bg-white px-5 py-3 text-gray-900 transition hover:text-gray-700 focus:outline-none focus:ring"
                    type = "Submit"> Hola, {{user.username}}. Cerrar Sesión</button>
                </form>
                {%else%}
                <a href = "{%url "login"%}">Login</a>
                {%endif%}     
               
              </button>
      
              <button
                class="inline-block rounded bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring"
                type="button"
              >
                Mi Pedido
              </button>
            </div>
          </div>
        </div>
      </header>

    <body>
        
        <div class = "container mx-auto px-4">
      
            {% block content%}

            {% endblock content%}               
        </div>
    </body>    
    <footer>
    </footer>

</html>

coffe_shop/user/templates/users/login.html
{% extends "base.html" %}
{% load tailwind_filters %}

{%block content%}
<h1 text-2xl font-bold text-gray-900 sm:text-3xl> Iniciar Sesión </h1>
<form action = "{% url "login"%}" method = 'post'>
    {% csrf_token %}
    {{ form|crispy }}
<button 
class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
type = "Submit">Login</button>
</form>

{%endblock content%}

coffe_shop/user/templates/users/register.html
{% load tailwind_filters %}
<form 
class = "mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8"
action = "{% url "create" %}" method = "post">
    {%csrf_token%}
    {{form | crispy}}

    <button
    class = "group relative inline-block text-sm font-medium text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
     type = "Submit"> Enviar </button>
</form>